# Pandas kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar!

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqlarni `📌Mavzulashtirdik`

## `📌Pandas kutubxonasini yuklash`

**1.** Pandas kutubxonasini `pd` nomi ostida yuklang va pandas kutubxonasini chop eting.

In [ ]:
import pandas as pd

**2.** Versiya va konfiguratsiyani tekshiring.

In [ ]:
pd.__version__

'2.2.2'

**3.** Pandas kutubxonasida mavjud bo'lgan barcha versiya ma'lumotlarini chop eting.

In [ ]:
pd.show_versions()

/usr/local/lib/python3.11/dist-packages/_distutils_hack/__init__.py:31: UserWarning: Setuptools is replacing distutils. Support for replacing an already imported distutils is deprecated. In the future, this condition will fail. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.11.12.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 6.1.123+
Version               : #1 SMP PREEMPT_DYNAMIC Sun Mar 30 16:01:29 UTC 2025
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : en_US.UTF-8
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.2
numpy                 : 2.0.2
pytz                  : 2025.2
dateutil              : 2.8.2
setuptools            : 75.2.0
pip                   : 24.1.2
Cython                : 3.0.12
pytest                : 8.3.5
hypothesis            : None
sphinx                : 8.2.3
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : 5.3.2
html5lib              : 1.1
pymysql               : None
psycopg2              : 2.9.10
jinja2                : 3.1.6
IPython               : 7.34.0
pandas_datareader     : 0.10.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.13.4
bottleneck            : 1.4.2
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2025.3.2
gcsfs                 : 2025.3.2
matplotlib            : 3.10.0
numba                 : 0.60.0
numexpr               : 2.10.2
odfpy                 : None
openpyxl              : 3.1.5
pandas_gbq            : 0.28.0
pyarrow               : 18.1.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.14.1
sqlalchemy            : 2.0.40
tables                : 3.10.2
tabulate              : 0.9.0
xarray                : 2025.1.2
xlrd                  : 2.0.1
zstandard             : 0.23.0
tzdata                : 2025.2
qtpy                  : None
pyqt5                 : None

## `📌DataFrame: Asoslar`

DataFrames-da ma'lumotlarni tanlash(selecting), saralash(sorting), qo'shish(adding) va yig'ish(aggregating) uchun bir nechta asosiy mashqlar.

💡Eslatma: NumPy kutubxonasini import qilishni unutmang:
``` python
import numpy as np
```

Quyidagi Python lug'ati(dictionary) `data` va Python ro'yxati(list) `labels` ni ko'rib chiqing:


``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

In [ ]:
import numpy as np

In [ ]:
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}
pd.DataFrame(data)

  animal  age  visits priority
0    cat  2.5       1      yes
1    cat  3.0       3      yes
2  snake  0.5       2       no
3    dog  NaN       3      yes
4    dog  5.0       2       no
5    cat  2.0       3       no
6  snake  4.5       1       no
7    cat  NaN       1      yes
8    dog  7.0       2       no
9    dog  3.0       1       no

In [ ]:
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
print(labels)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

**4.** Ushbu `lug'at`(dictionary) yordamida `data` dan `labels` indeksiga ega DataFrame yarating.

In [ ]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index = labels)
df                                           # (Dasturni davom ettiring!)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**5.** Ushbu DataFrame va uning ma'lumotlari haqidagi asosiy ma'lumotlarning qisqacha mazmunini ko'rsating.

`💡Ishora:` DataFrame-da chaqirilishi mumkin bo'lgan yagona usul mavjud.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   animal    10 non-null     object
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 700.0+ bytes

**6.** DataFrame `df` dastlabki 3 qatorini qaytaring.

In [ ]:
df.head(3)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

**7.** DataFrame `df`-dan faqat `animal` va `age` ustunlarini tanlang.

In [ ]:
df[['animal', 'age']]

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

**8.** `[3, 4, 8]` va `['animal', 'age']` qatorlaridagi ma'lumotlarni tanlang.

In [ ]:

df.loc[['d','e','i'], ['animal', 'age']]

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

**9.** Faqat `visits` soni 3 tadan ko'p bo'lgan qatorlarni tanlang.

In [ ]:
df[df['visits']>3]           # 3tadan ko'pi yo'q ekan

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

10. Yosh yo'qolgan qatorlarni tanlang, ya'ni `NaN`

In [ ]:
df[df['age'].isna()]

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

**11.** `animal` qatoridagi `cat` va `age` qatoridagi `3` dan kichik bo'lgan umumiy qatorlarni tanlang.

In [ ]:
df[(df['animal'] == 'cat') & (df['age'] >3)]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

**12.** `age` 2 va 4 (shu jumladan) orasidagi qatorlarni tanlang.

**13.** `f` qatoridagi yoshni `1,5` ga o'zgartiring.

In [ ]:
df.loc['f', 'age'] = 1.5

In [ ]:
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**14.** `df` yordamida `visits` qatorining yig'indisini hisoblang.

In [ ]:
df['visits'].sum()

np.int64(19)

**15.** Har bir `animal` uchun o'rtacha yoshni `df` da hisoblang.

In [ ]:
df.groupby('animal')['age'].mean()

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

**16.** `df` yordamida har bir turdagi `animal` sonini hisoblang.

In [ ]:
df['animal'].value_counts()

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

**17.** `animal` ustunida, `snake` so'zini `python` so'ziga o'zgartiring.

In [ ]:
df['animal'] = df['animal'].replace('snake', 'python')
df

   animal  age  visits priority
a     cat  2.5       1      yes
b     cat  3.0       3      yes
c  python  0.5       2       no
d     dog  NaN       3      yes
e     dog  5.0       2       no
f     cat  1.5       3       no
g  python  4.5       1       no
h     cat  NaN       1      yes
i     dog  7.0       2       no
j     dog  3.0       1       no

## `📌DataFrame: Murakkab`

### Bir oz qiyinroq: to'g'ri javob olish uchun ikki yoki undan ortiq usullarni birlashtirish kerak bo'lishi mumkin

Oldingi bo'lim DataFrame-ning asosiy, ammo muhim operatsiyalari bo'yicha vazifalarni jamlagan edi. Quyida ma'lumotlarni kesishingiz kerak bo'lgan mashqlar mavjud.

**18.** Sizda butun sonlardan iborat `A` ustunli DataFrame `df` mavjud. Misol uchun:
```python
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
```

Yuqoridagi qator bilan bir xil butun sonni o'z ichiga olgan qator yarating.


💡Sizda quyidagi qiymatlarni o'z ichiga olgan ustun paydo bo'lishi kerak:

```python
1, 2, 3, 4, 5, 6, 7
```

In [ ]:
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
df

    A
0   1
1   2
2   2
3   3
4   4
5   5
6   5
7   5
8   6
9   7
10  7

**19.** Raqamli qiymatlardan iborat DataFrame berildi

```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # float qiymatlarining 5x3 o'lchovi
```

Qatordagi har bir elementdan satrning o'rtacha qiymatini qanday ayirish mumkin?

In [ ]:
df = pd.DataFrame(np.random.random(size=(5, 3)))
result = df.sub(df.mean(axis=1), axis = 0)
result

          0         1         2
0  0.162077  0.234442 -0.396519
1  0.121508 -0.105034 -0.016474
2  0.123167  0.036652 -0.159820
3  0.080773 -0.042063 -0.038710
4  0.096025 -0.008173 -0.087852

**20.** Sizda 10 ta haqiqiy raqamlar ustunidan iborat DataFrame mavjud:

``` python
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
```
Qaysi sonlar ustunining yig'indisi eng kichik ekanini hisoblang. U ustunning yorlig'ini qaytaring.

In [ ]:
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
res = df.sum().idxmin()
res

'a'

**21.** Quyida butun sonlardan iborat DataFrame `df` mavjud. Har bir satrga  5 ta yozuv `NaN` qiymatlari kiritilgan.

DataFrame ning har bir qatori uchun uchinchi `NaN` qiymatini o'z ichiga olgan ustunni toping.

Ustun yorliqlarini qaytarishingiz kerak: `e, c, d, h, d`

In [ ]:
nan = np.nan
data = [[0.04,  nan,  nan, 0.25,  nan, 0.43, 0.71, 0.51,  nan,  nan],
        [ nan,  nan,  nan, 0.04, 0.76,  nan,  nan, 0.67, 0.76, 0.16],
        [ nan,  nan, 0.5 ,  nan, 0.31, 0.4 ,  nan,  nan, 0.24, 0.01],
        [0.49,  nan,  nan, 0.62, 0.73, 0.26, 0.85,  nan,  nan,  nan],
        [ nan,  nan, 0.41,  nan, 0.05,  nan, 0.61,  nan, 0.48, 0.68]]

columns = list('abcdefghij')

df = pd.DataFrame(data, columns=columns)
res = df.isna().cumsum(axis = 1).eq(3).idxmax(axis = 1)
res

# Javobni bu yerga yozing!

0    e
1    c
2    d
3    h
4    d
dtype: object

**22.** DataFrame `grps` guruhlari ustuniga va `vals` butun qiymatlari ustuniga ega:

```python
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
```
Har bir `grps` uchun uchta eng katta qiymatning yig‘indisini toping.

💡Javobni quyidagicha yakunlashingiz kerak:
```
grps
a    409
b    156
c    345
```

     'a   a  a b  b  c a a  b  c  c   c  b  b  c'
      12,345,3,1,45,14,4,52,54,23,235,21,57,3,87

In [ ]:
# Javobni bu yerga yozing!
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
#df
natija = df.groupby('grps')['vals'].sum()
natija

grps
a    416
b    160
c    380
Name: vals, dtype: int64

**23.** Quyida tuzilgan DataFrame `df` ikkita butun son ustuniga ega 'A' va 'B'. "A" dagi qiymatlar 1 dan 100 gacha (shu jumladan).

“A” dagi har bir 10 ta ketma-ket butun sonlar guruhi uchun (ya’ni `(0, 10]`, `(10, 20]`, ...) 'B' ustunidagi mos qiymatlar yig'indisini hisoblang.

Javob quyidagicha bo'lishi kerak:

```
A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
```

In [ ]:
df = pd.DataFrame(np.random.RandomState(8765).randint(1, 101, size=(100, 2)), columns = ["A", "B"])
result = df.groupby(pd.cut(df['A'], bins = [0,10,20,30,40,50,60,70,80,90,100]))['B'].sum()
result
# Javobni bu yerga yozing!

<ipython-input-49-e50e479656a9>:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  result = df.groupby(pd.cut(df['A'], bins = [0,10,20,30,40,50,60,70,80,90,100]))['B'].sum()

A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
Name: B, dtype: int64

**24.** 'X' butun son ustuni bo'lgan DataFrame:
```python
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
```

Har bir qiymat uchun farqni oldingi nolga qaytaring.

Sizda natija quyidagicha bo'lishi kerak:

```
[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]
```

Buni yangi `Y` ustuni deb nomlang.

In [ ]:
#javobni bu yerga yozing!
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
mask = (df['X'] == 0).cumsum()
nat = df['farq'] = df.groupby(mask).cumcount()
nat

0    0
1    1
2    0
3    1
4    2
5    3
6    4
7    0
8    1
9    2
dtype: int64

##`📌Ma'lumotlarni tozalash`

Bu har doim sodir bo'ladi: kimdir sizga noto'g'ri tuzilgan satrlar, ro'yxatlar va yetishmayotgan ma'lumotlarni o'z ichiga olgan ma'lumotlarni beradi. Tahlilni davom ettirish uchun uni qanday tartibga keltirasiz?

**25.** Quyidagi jumboqni tasavvur qilishi uchun ushbu misolni DataFrame sifatida oling:

```python
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})
```
Tartiblaganingizdan so'ng u quyidagi ko'rinishga ega bo'lishi kerak:

```
            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"
```

In [ ]:
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})
df

            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"

**26.** **FlightNumber** ustunidagi ba'zi qiymatlar yo'q. Ular `NaN` ko'rinishida yozilgan. Bu raqamlar har bir qatorda 10 ga ko'payishi kerak, shuning uchun 10055 va 10075 ni qo'yish kerak. Ushbu yetishmayotgan raqamlarni to'ldirish uchun `df` ni o'zgartiring va ustunni butun son ustuniga aylantiring.

In [ ]:
df['FlightNumber'] = df['FlightNumber'].ffill()  + df['FlightNumber'].isna().cumsum()*10

In [ ]:
df[['From', 'To']] = df['From_To'].str.split('_', expand=True)
df

   FlightNumber  RecentDelays              Airline      From         To
0       10045.0      [23, 47]               KLM(!)    LoNDon      paris
1       10055.0            []    <Air France> (12)    MAdrid      miLAN
2       10075.0  [24, 43, 87]  (British Airways. )    londON  StockhOlm
3       10085.0          [13]       12. Air France  Budapest      PaRis
4       10105.0      [67, 32]          "Swiss Air"  Brussels     londOn

**27.** **From\_To** ustunini ikkita alohida ustun ko'rinishida yozing.                                          

To'g'ri qiymatlarga ega `temp` deb nomlangan yangi Temporary DataFrame berish uchun har bir satrni pastki chiziq chegarasiga ajrating.                                                                     Ushbu Temporary DataFrame ustunlarini `From` va `To` deb nomlang.

In [ ]:
javobi tepada

**28.** Temporary DataFrame `temp` da shahar nomlari betartib yozilgan.Satrlarning faqat birinchi harfi katta yozilishi kerak.
                                                                         (Masalan, "londON" "London" bo'lishi kerak.)

In [ ]:
df['From'] = df ['From'].str.capitalize()
df['To'] = df['To'].str.capitalize()
df

   FlightNumber  RecentDelays              Airline      From         To
0       10045.0      [23, 47]               KLM(!)    London      Paris
1       10055.0            []    <Air France> (12)    Madrid      Milan
2       10075.0  [24, 43, 87]  (British Airways. )    London  Stockholm
3       10085.0          [13]       12. Air France  Budapest      Paris
4       10105.0      [67, 32]          "Swiss Air"  Brussels     London

**29**. `Airline` ustunida aviakompaniya nomlari atrofida qoʻshimcha tinish belgilari va belgilar paydo boʻlganini koʻrishingiz mumkin. Faqat aviakompaniya nomini qoldiring. Masalan, ʻ'(British Airways. )'' `British Airways` ko'rinishida yozilishi kerak.

In [ ]:
df['Airline'] = df['Airline'].str.replace(r'[^a-zA-Z\s]', '', regex = True)
df

   FlightNumber  RecentDelays         Airline      From         To
0       10045.0      [23, 47]             KLM    London      Paris
1       10055.0            []       AirFrance    Madrid      Milan
2       10075.0  [24, 43, 87]  BritishAirways    London  Stockholm
3       10085.0          [13]       AirFrance  Budapest      Paris
4       10105.0      [67, 32]        SwissAir  Brussels     London

**30.** `df` dan **From_To** ustunini o'chiring va Temporary DataFrame `temp` ustunini qo'shing.

In [ ]:
from_to ustunini tepada ochirib bolganman

**31**. `RecentDelays` ustunida qiymatlar DataFrame-ga ro'yxat sifatida kiritilgan. Sizning vazifangiz birinchi qiymatni o'z ustunida, har bir ikkinchi qiymatni o'z ustunida va qolgan qiymatlar ham ustunga mos holda chop etish. Agar N-chi qiymat bo'lmasa, qiymat `NaN` deb nomlanishi kerak.

Roʻyxatlar qatorini `delays` nomli DataFrame ichiga kengaytiring, `delay_1`, `delay_2` va qolgan ustunlarni ham nomlarini oʻzgartiring va `df` dagi keraksiz `RecentDelays` ustunini `delays` bilan almashtiring.

Natija quyidagi ko'rinishda bo'lishi kerak:
```
   FlightNumber          Airline      From         To  delay_1  delay_2  delay_3
0         10045              KLM    London      Paris     23.0     47.0      NaN
1         10055       Air France    Madrid      Milan      NaN      NaN      NaN
2         10065  British Airways    London  Stockholm     24.0     43.0     87.0
3         10075       Air France  Budapest      Paris     13.0      NaN      NaN
4         10085        Swiss Air  Brussels     London     67.0     32.0      NaN
```

In [ ]:
delays = df['RecentDelays'].apply(pd.Series)
delays.columns = ['delay_' + str(i + 1) for i in range(delays.shape[1])]
df = df.drop('RecentDelays', axis = 1).join(delays)                                 #kod togri ishladi Faqat recentdelaysni tashlab yuborganimga Key error berdi. Javobi pastda

KeyError: 'RecentDelays'

In [ ]:
df

,FlightNumber,Airline,From,To,delay_1,delay_2,delay_3
0,10045.0,KLM,London,Paris,23.0,47.0,NaN
1,10055.0,AirFrance,Madrid,Milan,NaN,NaN,NaN
2,10075.0,BritishAirways,London,Stockholm,24.0,43.0,87.0
3,10085.0,AirFrance,Budapest,Paris,13.0,NaN,NaN
4,10105.0,SwissAir,Brussels,London,67.0,32.0,NaN

##`📌Minesweeper`


### Minesweeper tarmog'ida xavfsiz kvadratlar uchun raqamlar yaratamiz!

💡 Agar siz Windowsning avvalgi versiyalaridan foydalangan bo'lsangiz, Minesweeper bilan tanishsiz:
- https://en.wikipedia.org/wiki/Minesweeper_(video_game)

Agar siz o'yin bilan tanish bo'lmasangiz, kvadratchalar to'plamini tasavvur qiling: bu kvadratlarning ba'zilari mineni yashiradi. Agar siz mineni bossangiz, darhol yo'qotasiz. Agar siz xavfsiz kvadratni bossangiz, darhol qo'shni bo'lgan kvadratchalarda qancha mine borligini ko'rsatadigan raqamni ko'rasiz. O'yinning maqsadi to'rdagi mine bo'lmagan barcha kvadratlarni ochishdir.

Ushbu bo'limda biz Minesweeper o'yini uchun kerakli ma'lumotlarni o'z ichiga olgan DataFrame yaratamiz: kvadratlarning koordinatalari, kvadratda mine bormi va qo'shni kvadratlarda topilgan minelar sonini aniqlaymiz!

**32**. Tasavvur qiling, biz Minesweeper o'yinini 5 dan 4 gacha bo'lgan panjarada o'ynayapmiz, ya'ni.
```
X = 5
Y = 4
```
Boshlash uchun ikkita ustunli DataFrame `df` yarating, bu tarmoq uchun har bir koordinatani o'z ichiga olgan `'x'` va `'y'`. Ya'ni DataFrame ishga tushishi kerak:
```
    x y
0 0 0
1 0 1
2 0 2
```

In [ ]:
x = list(range(5))
y = list(range(4))
coordinates = [(i,j) for i in x for j in y]
df = pd.DataFrame(coordinates, columns= ['x', 'y'])
df

    x  y
0   0  0
1   0  1
2   0  2
3   0  3
4   1  0
5   1  1
6   1  2
7   1  3
8   2  0
9   2  1
10  2  2
11  2  3
12  3  0
13  3  1
14  3  2
15  3  3
16  4  0
17  4  1
18  4  2
19  4  3

**33**. Ushbu DataFrame `df` uchun yangi nol (safe) va birliklar (mine) ustunini yarating. Har bir joyda mine sodir bo'lish ehtimoli 0,4 bo'lishi kerak.

In [ ]:
df['mine'] = np.random.choice([0,1], size = len(df), p = [0.6, 0.4])
df

    x  y  mine
0   0  0     1
1   0  1     1
2   0  2     1
3   0  3     1
4   1  0     0
5   1  1     0
6   1  2     1
7   1  3     0
8   2  0     0
9   2  1     1
10  2  2     1
11  2  3     0
12  3  0     0
13  3  1     1
14  3  2     1
15  3  3     1
16  4  0     0
17  4  1     0
18  4  2     1
19  4  3     0

 **34**. Endi ushbu DataFrame uchun `adjacent` nomli yangi ustun yarating. Ushbu ustunda tarmoqdagi qo'shni kvadratlarda topilgan minelar soni bo'lishi kerak.

(Masalan, `(0, 0)` koordinatasi uchun yozuv bo'lgan birinchi qator uchun `(0, 1)`, `(1, 0)` va `(1) koordinatalarida qancha mine borligini hisoblang. , 1)`.)

In [ ]:
adjacent_mines = []
for idx, row in df.iterrows():
    x, y = row['x'], row['y']
    neighbors = [(x-1, y-1), (x-1, y), (x-1, y+1), (x, y-1), (x, y+1), (x+1, y-1), (x+1, y), (x+1, y+1)]
    count = df[(df[['x', 'y']].apply(tuple, axis=1).isin(neighbors)) & (df['mine'] == 1)].shape[0]
    adjacent_mines.append(count)

df['adjacent'] = adjacent_mines

In [ ]:
df

    x  y  mine  adjacent
0   0  0     1         1
1   0  1     1         3
2   0  2     1         3
3   0  3     1         2
4   1  0     0         3
5   1  1     0         6
6   1  2     1         5
7   1  3     0         4
8   2  0     0         2
9   2  1     1         4
10  2  2     1         5
11  2  3     0         4
12  3  0     0         2
13  3  1     1         4
14  3  2     1         5
15  3  3     1         3
16  4  0     0         1
17  4  1     0         3
18  4  2     1         3
19  4  3     0         3

**35**. Mineni o'z ichiga olgan DataFrame qatorlari uchun `adjacent` ustunidagi qiymatni `NaN` ga o'zgartiring.

In [ ]:
df.loc[df['mine'] == 1, 'adjecent'] = np.nan

In [ ]:
df

    x  y  mine  adjacent  adjecent
0   0  0     1         1       NaN
1   0  1     1         3       NaN
2   0  2     1         3       NaN
3   0  3     1         2       NaN
4   1  0     0         3       NaN
5   1  1     0         6       NaN
6   1  2     1         5       NaN
7   1  3     0         4       NaN
8   2  0     0         2       NaN
9   2  1     1         4       NaN
10  2  2     1         5       NaN
11  2  3     0         4       NaN
12  3  0     0         2       NaN
13  3  1     1         4       NaN
14  3  2     1         5       NaN
15  3  3     1         3       NaN
16  4  0     0         1       NaN
17  4  1     0         3       NaN
18  4  2     1         3       NaN
19  4  3     0         3       NaN

**36**. DataFrame-ni `adjacent` minelar sonining panjarasiga aylantiring: ustunlar `x` koordinatasi, qatorlar `y` koordinatasi.

In [ ]:
grid = df.pivot(index = 'y', columns = 'x', values = 'adjecent')
grid

x   0   1   2   3   4
y
0 NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN

##📌BONUS!

O'zingiz javob berishni istagan savolni kiriting va unga javob bering!